### PR TITLE
Add new recipe

### PR DESCRIPTION
**Pull request by sofiavrebelo**
Sweet Rice Recipe

### CODE REVIEW

**Review by jlooper — CHANGES_REQUESTED** [review]
Hi, can you add a comma after the previous recipe to yours, or the build will break

**Comment by jlooper** [comment]
@sofiavrebelo a requested small change

**Comment by sofiavrebelo** [comment]
Thanks Jen! I ll correct it tomorrow morning!

A quarta, 7 de set de 2022, 20:53, Jen Looper ***@***.***>
escreveu:

**Review by jlooper — APPROVED** [review]
nice!

**Comment by sofiavrebelo** [comment]
Hi Jen, I noticed that the title of the recipe appears as "title of
recipe", so i'll try to send a pull request asap to correct that


Jen Looper ***@***.***> escreveu no dia sábado, 10/09/2022
à(s) 21:53:

**Pull request merged**
